import datetime
import functools
import pathlib
from decimal import Decimal

import pytest
from beanhub_extract.data_types import Fingerprint, Transaction
from beanhub_extract.extractors.fidelity import (
    FidelityExtractor,
    beanify_account,
    parse_date,
)
from beanhub_extract.utils import strip_txn_base_path


@pytest.mark.parametrize(
    "date_str, expected",
    [
        ("05/04/2024", datetime.date(2024, 5, 4)),
    ],
)
def test_parse_date(date_str: str, expected: datetime.date):
    assert parse_date(date_str) == expected


def test_beanify_account():
    assert beanify_account("Person (CASH)") == "Person-Cash"
    assert beanify_account("Other Person: CASH") == "Other-Person-Cash"
    assert beanify_account("Tech_Account 123") == "Tech_Account-123"


transactions = [
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=1,
        reversed_lineno=-24,
        transaction_id=None,
        date=datetime.date(2024, 3, 28),
        post_date=datetime.date(2024, 3, 28),
        timestamp=None,
        timezone=None,
        desc="REINVESTMENT FIDELITY GOVERNMENT MONEY MARKET (SPAXX) (Cash)",
        bank_desc="FIDELITY GOVERNMENT MONEY MARKET",
        amount=Decimal("-126.23"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/28/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "REINVESTMENT FIDELITY GOVERNMENT MONEY MARKET (SPAXX) (Cash)",
            "Symbol": "SPAXX",
            "Description": "FIDELITY GOVERNMENT MONEY MARKET",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "1",
            "Quantity": "126.23",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-126.23",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=2,
        reversed_lineno=-23,
        transaction_id=None,
        date=datetime.date(2024, 3, 22),
        post_date=datetime.date(2024, 3, 22),
        timestamp=None,
        timezone=None,
        desc="TRANSFERRED TO VS Z30-309107-1 (Cash)",
        bank_desc="No Description",
        amount=Decimal("-1500.01"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="3467",
        extra={
            "Run Date": "03/22/2024",
            "Account": "Person (CASH)",
            "Account Number": "Z26543467",
            "Action": "TRANSFERRED TO VS Z30-309107-1 (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-1500.01",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=3,
        reversed_lineno=-22,
        transaction_id=None,
        date=datetime.date(2024, 3, 22),
        post_date=datetime.date(2024, 3, 22),
        timestamp=None,
        timezone=None,
        desc="TRANSFERRED FROM VS Z26-543467-1 (Cash)",
        bank_desc="No Description",
        amount=Decimal("1500.01"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/22/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "TRANSFERRED FROM VS Z26-543467-1 (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "1500.01",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=4,
        reversed_lineno=-21,
        transaction_id=None,
        date=datetime.date(2024, 3, 18),
        post_date=datetime.date(2024, 3, 18),
        timestamp=None,
        timezone=None,
        desc="DIRECT DEBIT CAPITAL ONE ACCTVERIFY (Cash)",
        bank_desc="No Description",
        amount=Decimal("-0.23"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/18/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "DIRECT DEBIT CAPITAL ONE ACCTVERIFY (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-0.23",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=5,
        reversed_lineno=-20,
        transaction_id=None,
        date=datetime.date(2024, 3, 14),
        post_date=datetime.date(2024, 3, 14),
        timestamp=None,
        timezone=None,
        desc="Electronic Funds Transfer Received (Cash)",
        bank_desc="No Description",
        amount=Decimal("1500"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="3467",
        extra={
            "Run Date": "03/14/2024",
            "Account": "Person (CASH)",
            "Account Number": "Z26543467",
            "Action": "Electronic Funds Transfer Received (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "1500",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=6,
        reversed_lineno=-19,
        transaction_id=None,
        date=datetime.date(2024, 3, 12),
        post_date=datetime.date(2024, 3, 12),
        timestamp=None,
        timezone=None,
        desc="TRANSFERRED TO VS Z30-309107-1 (Cash)",
        bank_desc="No Description",
        amount=Decimal("-42811.99"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="3467",
        extra={
            "Run Date": "03/12/2024",
            "Account": "Person (CASH)",
            "Account Number": "Z26543467",
            "Action": "TRANSFERRED TO VS Z30-309107-1 (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-42811.99",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=7,
        reversed_lineno=-18,
        transaction_id=None,
        date=datetime.date(2024, 3, 12),
        post_date=datetime.date(2024, 3, 12),
        timestamp=None,
        timezone=None,
        desc="TRANSFERRED FROM VS Z26-543467-1 (Cash)",
        bank_desc="No Description",
        amount=Decimal("42811.99"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/12/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "TRANSFERRED FROM VS Z26-543467-1 (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "42811.99",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=8,
        reversed_lineno=-17,
        transaction_id=None,
        date=datetime.date(2024, 3, 8),
        post_date=datetime.date(2024, 3, 8),
        timestamp=None,
        timezone=None,
        desc="Electronic Funds Transfer Received (Cash)",
        bank_desc="No Description",
        amount=Decimal("4000"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/08/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "Electronic Funds Transfer Received (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "4000",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=9,
        reversed_lineno=-16,
        transaction_id=None,
        date=datetime.date(2024, 3, 6),
        post_date=datetime.date(2024, 3, 6),
        timestamp=None,
        timezone=None,
        desc="Electronic Funds Transfer Received (Cash)",
        bank_desc="No Description",
        amount=Decimal("-4000"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/06/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "Electronic Funds Transfer Received (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-4000",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=10,
        reversed_lineno=-15,
        transaction_id=None,
        date=datetime.date(2024, 3, 4),
        post_date=datetime.date(2024, 3, 4),
        timestamp=None,
        timezone=None,
        desc="Electronic Funds Transfer Received (Cash)",
        bank_desc="No Description",
        amount=Decimal("42811.99"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="3467",
        extra={
            "Run Date": "03/04/2024",
            "Account": "Person (CASH)",
            "Account Number": "Z26543467",
            "Action": "Electronic Funds Transfer Received (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "42811.99",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=11,
        reversed_lineno=-14,
        transaction_id=None,
        date=datetime.date(2024, 3, 4),
        post_date=datetime.date(2024, 3, 4),
        timestamp=None,
        timezone=None,
        desc="Electronic Funds Transfer Received (Cash)",
        bank_desc="No Description",
        amount=Decimal("4000"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Savings",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="9107",
        extra={
            "Run Date": "03/04/2024",
            "Account": "Savings",
            "Account Number": "Z30309107",
            "Action": "Electronic Funds Transfer Received (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "4000",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=12,
        reversed_lineno=-13,
        transaction_id=None,
        date=datetime.date(2024, 2, 29),
        post_date=datetime.date(2024, 2, 29),
        timestamp=None,
        timezone=None,
        desc="NON-RESIDENT TAX INTEREST RECEIVED FDIC INSURED DEPOSIT AT CITIBANK NOT... (QPCTQ) (Cash)",
        bank_desc="FDIC INSURED DEPOSIT AT CITIBANK NOT CO",
        amount=Decimal("-0.05"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Other-Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="6330",
        extra={
            "Run Date": "02/29/2024",
            "Account": "Other Person (CASH)",
            "Account Number": "Z27376330",
            "Action": "NON-RESIDENT TAX INTEREST RECEIVED FDIC INSURED DEPOSIT AT CITIBANK NOT... (QPCTQ) (Cash)",
            "Symbol": "QPCTQ",
            "Description": "FDIC INSURED DEPOSIT AT CITIBANK NOT CO",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-0.05",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=13,
        reversed_lineno=-12,
        transaction_id=None,
        date=datetime.date(2024, 2, 26),
        post_date=datetime.date(2024, 2, 26),
        timestamp=None,
        timezone=None,
        desc="DIRECT DEBIT VENMO ACCTVERIFY (Cash)",
        bank_desc="No Description",
        amount=Decimal("-0.01"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Other-Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="6330",
        extra={
            "Run Date": "02/26/2024",
            "Account": "Other Person (CASH)",
            "Account Number": "Z27376330",
            "Action": "DIRECT DEBIT VENMO ACCTVERIFY (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-0.01",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=14,
        reversed_lineno=-11,
        transaction_id=None,
        date=datetime.date(2024, 2, 26),
        post_date=datetime.date(2024, 2, 26),
        timestamp=None,
        timezone=None,
        desc="DIRECT DEBIT VENMO ACCTVERIFY (Cash)",
        bank_desc="No Description",
        amount=Decimal("-0.28"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Other-Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="6330",
        extra={
            "Run Date": "02/26/2024",
            "Account": "Other Person (CASH)",
            "Account Number": "Z27376330",
            "Action": "DIRECT DEBIT VENMO ACCTVERIFY (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-0.28",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=15,
        reversed_lineno=-10,
        transaction_id=None,
        date=datetime.date(2024, 2, 23),
        post_date=datetime.date(2024, 2, 23),
        timestamp=None,
        timezone=None,
        desc="Electronic Funds Transfer Received (Cash)",
        bank_desc="No Description",
        amount=Decimal("500"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Other-Person-Cash",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="6330",
        extra={
            "Run Date": "02/23/2024",
            "Account": "Other Person (CASH)",
            "Account Number": "Z27376330",
            "Action": "Electronic Funds Transfer Received (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "500",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=16,
        reversed_lineno=-9,
        transaction_id=None,
        date=datetime.date(2024, 1, 31),
        post_date=datetime.date(2024, 1, 31),
        timestamp=None,
        timezone=None,
        desc="NON-RESIDENT TAX DIVIDEND RECEIVED FIDELITY GOVERNMENT MONEY MARKET (SPAXX) (Cash)",
        bank_desc="FIDELITY GOVERNMENT MONEY MARKET",
        amount=Decimal("-0.21"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/31/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "NON-RESIDENT TAX DIVIDEND RECEIVED FIDELITY GOVERNMENT MONEY MARKET (SPAXX) (Cash)",
            "Symbol": "SPAXX",
            "Description": "FIDELITY GOVERNMENT MONEY MARKET",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-0.21",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=17,
        reversed_lineno=-8,
        transaction_id=None,
        date=datetime.date(2024, 1, 18),
        post_date=datetime.date(2024, 1, 18),
        timestamp=None,
        timezone=None,
        desc="JOURNALED RSU Refund (Cash)",
        bank_desc="No Description",
        amount=Decimal("-23.07"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/18/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "JOURNALED RSU Refund (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-23.07",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=18,
        reversed_lineno=-7,
        transaction_id=None,
        date=datetime.date(2024, 1, 18),
        post_date=datetime.date(2024, 1, 18),
        timestamp=None,
        timezone=None,
        desc="JOURNALED RSU CA SDI (Cash)",
        bank_desc="No Description",
        amount=Decimal("-134.75"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/18/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "JOURNALED RSU CA SDI (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-134.75",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=19,
        reversed_lineno=-6,
        transaction_id=None,
        date=datetime.date(2024, 1, 18),
        post_date=datetime.date(2024, 1, 18),
        timestamp=None,
        timezone=None,
        desc="JOURNALED RSU Medicare (Cash)",
        bank_desc="No Description",
        amount=Decimal("-177.62"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/18/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "JOURNALED RSU Medicare (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-177.62",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=20,
        reversed_lineno=-5,
        transaction_id=None,
        date=datetime.date(2024, 1, 18),
        post_date=datetime.date(2024, 1, 18),
        timestamp=None,
        timezone=None,
        desc="JOURNALED RSU Social Security (Cash)",
        bank_desc="No Description",
        amount=Decimal("-759.49"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/18/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "JOURNALED RSU Social Security (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-759.49",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=21,
        reversed_lineno=-4,
        transaction_id=None,
        date=datetime.date(2024, 1, 18),
        post_date=datetime.date(2024, 1, 18),
        timestamp=None,
        timezone=None,
        desc="JOURNALED RSU CA State Income (Cash)",
        bank_desc="No Description",
        amount=Decimal("-1253.15"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/18/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "JOURNALED RSU CA State Income (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-1253.15",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=22,
        reversed_lineno=-3,
        transaction_id=None,
        date=datetime.date(2024, 1, 18),
        post_date=datetime.date(2024, 1, 18),
        timestamp=None,
        timezone=None,
        desc="JOURNALED RSU US Federal Incom (Cash)",
        bank_desc="No Description",
        amount=Decimal("-2694.95"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/18/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "JOURNALED RSU US Federal Incom (Cash)",
            "Symbol": "",
            "Description": "No Description",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "0.000",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "-2694.95",
            "Settlement Date": "",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=23,
        reversed_lineno=-2,
        transaction_id=None,
        date=datetime.date(2024, 1, 17),
        post_date=datetime.date(2024, 1, 17),
        timestamp=None,
        timezone=None,
        desc="YOU BOUGHT RSU#### AS OF 01-16-24 AMAZON.COM INC (AMZN) (Cash)",
        bank_desc="AMAZON.COM INC",
        amount=Decimal("0.00"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/17/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "YOU BOUGHT RSU#### AS OF 01-16-24 AMAZON.COM INC (AMZN) (Cash)",
            "Symbol": "AMZN",
            "Description": "AMAZON.COM INC",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "",
            "Quantity": "80",
            "Exchange Rate": "0",
            "Commission": "",
            "Fees": "",
            "Accrued Interest": "",
            "Amount": "0.00",
            "Settlement Date": "01/18/2024",
        },
    ),
    Transaction(
        extractor="fidelity",
        file="fidelity.csv",
        lineno=24,
        reversed_lineno=-1,
        transaction_id=None,
        date=datetime.date(2024, 1, 17),
        post_date=datetime.date(2024, 1, 17),
        timestamp=None,
        timezone=None,
        desc="YOU SOLD VSP02411600000012531AS OF 01-16-24 AMAZON.COM INC (AMZN) (Cash)",
        bank_desc="AMAZON.COM INC",
        amount=Decimal("5043.03"),
        currency="USD",
        category=None,
        subcategory=None,
        pending=None,
        status=None,
        type="Cash",
        source_account="Tech",
        dest_account=None,
        note=None,
        reference=None,
        payee=None,
        gl_code=None,
        name_on_card=None,
        last_four_digits="2922",
        extra={
            "Run Date": "01/17/2024",
            "Account": "TECH",
            "Account Number": "Z28412922",
            "Action": "YOU SOLD VSP02411600000012531AS OF 01-16-24 AMAZON.COM INC (AMZN) (Cash)",
            "Symbol": "AMZN",
            "Description": "AMAZON.COM INC",
            "Type": "Cash",
            "Exchange Quantity": "0",
            "Exchange Currency": "",
            "Currency": "USD",
            "Price": "153.12",
            "Quantity": "-33",
            "Exchange Rate": "0",
            "Commission": "9.95",
            "Fees": "0.05",
            "Accrued Interest": "",
            "Amount": "5043.03",
            "Settlement Date": "01/18/2024",
        },
    ),
]


@pytest.mark.parametrize(
    "input_file, expected",
    [
        (
            "fidelity.csv",
            transactions,
        )
    ],
)
def test_extractor(
    fixtures_folder: pathlib.Path, input_file: str, expected: list[Transaction]
):
    with open(fixtures_folder / input_file) as fo:
        extractor = FidelityExtractor(fo)
        assert (
            list(
                map(
                    functools.partial(strip_txn_base_path, fixtures_folder), extractor()
                )
            )
            == expected
        )


def test_fingerprint(fixtures_folder: pathlib.Path):
    input_file = fixtures_folder / "fidelity.csv"
    with open(input_file, "rt") as fo:
        extractor = FidelityExtractor(fo)
        assert (
            pathlib.Path(extractor.input_file.name).name
            == pathlib.Path(input_file).name
        )

        for tr in extractor():
            if tr.source_account is not None:
                if "Other Person" in tr.source_account:
                    assert tr.source_account == "Other-Person-Cash"


# @pytest.mark.parametrize(
#     "input_file",
#     ["fidelity.csv"],
# )
# def test_transactions(fixtures_folder: pathlib.Path, input_file: str):
#     with open(fixtures_folder / input_file, "rt") as fo:
#         extractor = FidelityExtractor(fo)
#         for tr in extractor():
#             print(tr)
